project: 
  type: manuscript
  output-dir: docs
title: "ESS330: Final Project"
subtitle: "Lab 9"
authors: 
  - name: Olivia Gilpin
    affiliation: Colorado State University
    roles: [writing]
    corresponding: true
  - name: Josh Ray
    affiliation: Colorado State University
    roles: [writing]
format:
  html:
    self-contained: true 
    toc: true
    toc-depth: 5
    toc-location: left
    toc-title: "Table of Contents"
    include-in-header:
      text: |
        <style>
          /* Hide the notebooks sidebar section */
          .sidebar-item-container .sidebar-item:has(> .sidebar-item-text:contains("Notebooks")),
          .sidebar-item-section h2:contains("Notebooks"),
          .sidebar-item-section:has(h2:contains("Notebooks")) {
            display: none !important;
          }
        </style>
execute:
  echo: true
editor: visual
bibliography: references.bib
csl: apa-6th-edition.csl